; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
board = nucleo_f303k8
framework = stm32cube
upload_protocol = stlink
monitor_speed = 115200
monitor_filters = direct
upload_flags =
  -c
  set WORKAREASIZE 0x3000

build_flags =
  -Iinclude
  -Isrc
  -DSTM32F303x8

[env:nucleo_f303k8]
build_type = release

[env:nucleo_f303k8_debug]
build_type = debug
build_flags =
  ${env.build_flags}
  -DDEBUG_LOG_ENABLED=1
